name: TamableFoxes
version: 1.4.1-SNAPSHOT
main: net.seanomik.tamablefoxes.TamableFoxes
api-version: 1.15
load: POSTWORLD
description: Modified version of TamableFoxes for 1.15.1.

commands:
  spawntamablefox:
    aliases: [tamablefox, stf, spawntf]
    usage: /spawntamablefox [type]
    description: Spawn a tamable fox at the standing location. Type can be snow or red, or left empty for a red.
permissions:
  tamablefoxes.spawn:
    description: "Gives the player the ability to spawn tamable foxes."
    default: false
