name: Tamablefoxes
version: 1.5.2-SNAPSHOT
main: net.seanomik.tamablefoxes.TamableFoxes
api-version: 1.15
load: POSTWORLD
description: Adds tamable foxes to Minecraft!

commands:
  spawntamablefox:
    aliases: [tamablefox, stf, spawntf]
    usage: /spawntamablefox [type]
    description: Spawn a tamable fox at the standing location. Type can be snow or red, or left empty for a red.
permissions:
  tamablefoxes.spawn:
    description: "Gives the player the ability to spawn tamable foxes."
    default: false
  tamablefoxes.tame:
    description: "Gives the player the ability to tame a fox."
    default: false
