# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.1.1
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    #- name: Compile Spigot
    #  uses: SeanOMik/Action-SpigotMC@b23370e6a4c3e9cdd38b8d5bcd4a543f8c1e1c19
    #  with:
    #    versions: 1.14,1.15,1.16.1,1.16.3,1.16.5,1.17
    #    threads: -1
    #    remapped: remapped-mojang
    - name: Compile Remapped Mojang Spigot
      uses: SeanOMik/Action-SpigotMC@b23370e6a4c3e9cdd38b8d5bcd4a543f8c1e1c19
      with:
        versions: 1.17
        threads: -1
        remapped: remapped-mojang
    - name: Install with Maven
      run: |
        sudo mvn install
    - name: Build with Maven
      run: |
        sudo mvn package
